[workspace]
members = ["src-tauri"]

[package]
name = "lokalvault"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "lokalvault"
path = "src/main.rs"

[dependencies]
aes-gcm  = "0.10"
argon2   = "0.5"
rand     = { version = "0.8", features = ["getrandom"] }
zeroize  = { version = "1", features = ["derive"] }
hex      = "0.4"
serde      = { version = "1", features = ["derive"] }
serde_json = "1"
tokio      = { version = "1", features = ["full"] }
clap       = { version = "4", features = ["derive"] }
subtle     = "2"
rpassword  = "7"
chrono     = { version = "0.4", features = ["serde"] }
clap_complete = "4"
toml = "0.8"
arboard = "3"
notify = "6"
zxcvbn = "3"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[lib]
name = "lokalvault"
path = "src/lib.rs"
